// Mocks generated by Mockito 5.0.13 from annotations
// in fii_app/test/core/data/repositories/default_reit_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:fii_app/core/data/datasources/reit_data_source.dart' as _i2;
import 'package:fii_app/core/data/models/reit_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ReitDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockReitDataSource extends _i1.Mock implements _i2.ReitDataSource {
  MockReitDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ReitModel>> getAll() =>
      (super.noSuchMethod(Invocation.method(#getAll, []),
              returnValue: Future<List<_i4.ReitModel>>.value(<_i4.ReitModel>[]))
          as _i3.Future<List<_i4.ReitModel>>);
  @override
  String toString() => super.toString();
}
