name: fii_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.1
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  html: ^0.15.0
  http: ^0.13.3
  intl: ^0.17.0
  mobx: ^2.0.3

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.0
  lint: ^1.0.0
  mobx_codegen: ^2.0.2
  mockito: ^5.0.13
  http_mock_adapter: ^0.3.2

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/launcher_icon.png"

flutter_native_splash:
  color: "#181697"
  image: "assets/images/icons/splash_icon.png"
