name: fii_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.1
  mobx: ^2.0.3
  get_it: ^7.2.0
  dio: ^4.0.0
  intl: ^0.17.0
  html: ^0.15.0
  google_fonts: ^2.1.0
  dartz: ^0.10.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  lazy_data_table: ^0.3.0
  flutter_xlider:
    git:
      url: https://github.com/Ali-Azmoud/flutter_xlider.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.0
  build_runner: ^2.0.6
  mobx_codegen: ^2.0.2
  mockito: ^5.0.13
  http_mock_adapter: ^0.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/launcher_icon.png"

flutter_native_splash:
  color: "#0084FF"
  image: "assets/images/icons/splash_icon.png"

executables:
  mobx_watch: flutter pub run build_runner watch --delete-conflicting-outputs
