// Mocks generated by Mockito 5.0.13 from annotations
// in fii_app/test/shared/repositories/reit_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dio/src/dio.dart' as _i2;
import 'package:fii_app/shared/datasources/funds_explorer_datasource.dart'
    as _i3;
import 'package:fii_app/shared/models/reit.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeDio extends _i1.Fake implements _i2.Dio {}

/// A class which mocks [FundsExplorerDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFundsExplorerDatasource extends _i1.Mock
    implements _i3.FundsExplorerDatasource {
  MockFundsExplorerDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get http =>
      (super.noSuchMethod(Invocation.getter(#http), returnValue: _FakeDio())
          as _i2.Dio);
  @override
  String get url =>
      (super.noSuchMethod(Invocation.getter(#url), returnValue: '') as String);
  @override
  _i4.Future<List<_i5.Reit>> getAll() =>
      (super.noSuchMethod(Invocation.method(#getAll, []),
              returnValue: Future<List<_i5.Reit>>.value(<_i5.Reit>[]))
          as _i4.Future<List<_i5.Reit>>);
  @override
  String toString() => super.toString();
}
